export function TermsOfServicePage() {
    return (
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-16 max-w-4xl">
            <div className="mb-10">
                <h1 className="text-4xl font-display font-bold tracking-tight text-text-primary mb-3">Terms of Service</h1>
                <p className="text-sm text-text-secondary">Last updated: April 2026</p>
            </div>

            <div className="bg-amber-50 border border-amber-100 rounded-xl p-5 mb-10">
                <p className="text-sm text-amber-800 leading-relaxed">
                    <strong>Plain-language note:</strong> ProductLogik is a solo-built MVP. By using it, you accept that the service is provided as-is, without guarantees of uptime, accuracy, or fitness for any particular purpose. These terms are written honestly to reflect that reality.
                </p>
            </div>

            <div className="space-y-8 text-sm text-text-secondary leading-relaxed">
                <PolicySection title="1. Acceptance of Terms">
                    <p>
                        By creating an account or using ProductLogik in any capacity, you agree to these Terms of Service. If you do not agree, please do not use the service.
                    </p>
                </PolicySection>

                <PolicySection title="2. Description of Service">
                    <p>
                        ProductLogik is a web application that accepts CSV files containing feedback data and uses AI (Google Gemini) to extract themes, sentiment analysis, and executive summaries. The service is operated by an independent developer and is provided on a best-effort basis.
                    </p>
                </PolicySection>

                <PolicySection title="3. Account Eligibility">
                    <p>
                        You must be at least 16 years old to create an account. By registering, you represent that you are legally capable of entering into a binding agreement and that the information you provide is accurate.
                    </p>
                </PolicySection>

                <PolicySection title="4. Acceptable Use">
                    <p>You agree not to:</p>
                    <ul className="list-disc pl-5 space-y-1 mt-2">
                        <li>Upload files containing personally identifiable information (PII) of individuals who have not consented to AI processing</li>
                        <li>Use the service to process data in violation of any applicable law or regulation</li>
                        <li>Attempt to reverse-engineer, scrape, or abuse the API or underlying infrastructure</li>
                        <li>Create multiple accounts to circumvent usage limits</li>
                    </ul>
                </PolicySection>

                <PolicySection title="5. Intellectual Property">
                    <p>
                        The analysis results generated by ProductLogik are yours to use. The application code, design, and branding remain the intellectual property of Hamza Latif. You may not reproduce or redistribute the platform itself.
                    </p>
                </PolicySection>

                <PolicySection title="6. Disclaimer of Warranties">
                    <p>
                        ProductLogik is provided <strong>"as is"</strong> without any warranty of any kind — express, implied, or statutory. This includes, but is not limited to, implied warranties of merchantability, fitness for a particular purpose, or non-infringement. The AI-generated analysis is a decision-support tool, not a professional advisory service. You are solely responsible for how you act on any insights produced.
                    </p>
                </PolicySection>

                <PolicySection title="7. Limitation of Liability">
                    <p>
                        To the maximum extent permitted by applicable law, the developer shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of, or inability to use, the service — including data loss, business interruption, or inaccurate AI outputs.
                    </p>
                </PolicySection>

                <PolicySection title="8. Service Availability">
                    <p>
                        As a solo-built MVP, ProductLogik does not guarantee any specific level of uptime or availability. The service may experience outages due to infrastructure maintenance, third-party API changes, or unforeseen technical issues. There is no SLA.
                    </p>
                </PolicySection>

                <PolicySection title="9. Governing Law">
                    <p>
                        These terms are governed by the laws of the jurisdiction of the independent developer's primary residence. Disputes will be resolved under applicable international digital commerce conventions. No specific jurisdiction, court, or arbitration body is named, as this is a personal project without a registered legal entity.
                    </p>
                </PolicySection>

                <PolicySection title="10. Changes to Terms">
                    <p>
                        These terms may be updated at any time. Material changes will be communicated to registered users by email. Continued use of the service after changes constitutes acceptance of the revised terms.
                    </p>
                </PolicySection>

                <PolicySection title="11. Contact">
                    <p>
                        For questions about these terms, contact <a href="mailto:contact@hamzalatif.com" className="text-brand-600 hover:text-brand-700">contact@hamzalatif.com</a>.
                    </p>
                </PolicySection>
            </div>
        </div>
    );
}

function PolicySection({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <div>
            <h2 className="text-base font-display font-bold text-text-primary mb-3">{title}</h2>
            <div className="space-y-2 text-justify">{children}</div>
        </div>
    );
}
